# Site settings
title: blog
email: 
description: "Musings of a confused scientist."
baseurl: ""
url: "http://kenyiwoosh.github.io"
twitter_username: Renzo64216429
github_username:  TAOGenna

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
