baseurl: ""  # Since your site is hosted at the root domain, leave this empty
url: "https://kenyiwoosh.github.io"  # Your GitHub Pages URL

title: Tufte-Jekyll
subtitle: Content-centric blogging
author: Kenyi Woosh  # Update with your name
simple_search: http://google.com/search
description: A Jekyll theme for content-rich sites
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York  # Update this to your actual timezone if necessary
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
